### ISSUE TITLE
Just installed 0.7.1 - django.core.exceptions.ImproperlyConfigured

### ISSUE THREAD

**Issue by apaxson** [CarliJoy/django-pint#87]
Just installed 0.7.1 using PIP with Django 4.2.2 and Python 3.9.6

I added a single field in my models using QuantityField to test.  Upon testing using Django Shell, i get the following:

```
>>> from quantityfield.fields import QuantityField


Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/webroot/venv/lib/python3.9/site-packages/quantityfield/fields.py", line 17, in <module>
    from .units import ureg
  File "/webroot/venv/lib/python3.9/site-packages/quantityfield/units.py", line 1, in <module>
    from .settings import DJANGO_PINT_UNIT_REGISTER
  File "webroot/venv/lib/python3.9/site-packages/quantityfield/settings.py", line 7, in <module>
    DJANGO_PINT_UNIT_REGISTER = getattr(
  File "/webroot/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 102, in __getattr__
    self._setup(name)
  File "/webroot/venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in _setup
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Requested setting DJANGO_PINT_UNIT_REGISTER, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
>>>
``` 

While I'm told the settings.py file gets auto-added with the default registry, I still get this message.  I tried manually adding this following to settings.py but it doesn't resolve the error:

```
from pint import UnitRegistry
DJANGO_PINT_UNIT_REGISTER = UnitRegistry()
```

Any thoughts?  I understand you're not actively developing, and I'm happy to help identify the solution for others.  Just need a little direction.

**Comment by apaxson** [comment]
I resolved this by executing from terminal "export DJANGO_SETTINGS_MODULE=settings" and then exiting my terminal and re-opening.

**Comment by CarliJoy** [comment]
Ok seems like you resolved the issue ;-)

Can we close this?
